### ISSUE TITLE
suggestion: include 'moveit' in pkg name?

### ISSUE THREAD

**Issue by gavanderhoorn** [JeroenDM/moveit_opw_kinematics_plugin#1]
It might be good to add `moveit` somewhere in the package name so as to better convey the fact that this package provides a plugin that is compatible with the MoveIt `KinematicsBase` class.

I realise that most IKFast plugins (fi) don't do this, and most of MoveIt's own plugins also don't do this, but we can start somewhere :)

Perhaps `moveit_opw_kinematics_plugin` or something similar?

---

Edit: see also [REP-144](http://www.ros.org/reps/rep-0144.html).

**Comment by gavanderhoorn** [comment]
:+1: for working on this btw.

**Comment by JeroenDM** [comment]
Thanks for the suggestion.
I changed the package name. But I'm not sure how far I have to go with renaming.
Do I also rename the class OPWKinematicsPlugin and source and header file?

**Comment by gavanderhoorn** [comment]
That would seem to be the most consistent, but it's up to you.

**Comment by JeroenDM** [comment]
I like consistency, but with those names, it's a good thing we have tab completion...
