### ISSUE TITLE
License again

### ISSUE THREAD

**Issue by simonschmeisser** [JeroenDM/moveit_opw_kinematics_plugin#10]
Hi Jeroen,

not sure if I overlooked something but I have the impression that while we now have a proper license in opw_kinematics (https://github.com/Jmeyer1292/opw_kinematics/issues/11) there still is no such information given here?

Thanks
Simon

**Comment by JeroenDM** [comment]
I'm sorry, I added a license to a bunch of my repositories but forgot this one.
Thanks for the reminder!

**Comment by simonschmeisser** [comment]
Thanks!
