### ISSUE TITLE
mismatch between signcorrections in test and readme

### ISSUE THREAD

**Issue by simonschmeisser** [JeroenDM/moveit_opw_kinematics_plugin#16]
https://github.com/JeroenDM/moveit_opw_kinematics_plugin/blob/97877b0ed249579c7defdffe5bd86607b717c542/test/kinematics_kuka.yaml#L13

has all positive sign correction while the readme (and kuka in reality) have 1,4 and 6 negative

cannot run the test as I don't have this variant of the kuka package

ps: thanks for your continued work!

**Comment by JeroenDM** [comment]
Mmm, your right, there must be a bug somewhere.
I suspect the test is using [this kinematics.yaml](https://github.com/JeroenDM/kuka_kr6r700_moveit_config/blob/23cd9ac5c0890f27a8979b4eb3b39d956c535359/config/kinematics.yaml), although that was [not my intention](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/blob/97877b0ed249579c7defdffe5bd86607b717c542/test/test_kuka.rostest#L8). I will fix this.

**Comment by JeroenDM** [comment]
Ok, it seems the right file (with the wrong parameters) is loaded. But the current tests don't catch errors in sign corrections. I'm adding a small test for this specific robot. But this again stresses the fact that I need tests that check consistency with the urdf.

**Comment by JeroenDM** [comment]
I changed the parameters 0b052f498596571ac28abbf854e81013c8c14c2b
Thanks for pointing it out!

I also added a (quick and dirty) test to make sure I don't change them again.
