### ISSUE TITLE
Remove "Moveit" prefix

### ISSUE THREAD

**Issue by simonschmeisser** [JeroenDM/moveit_opw_kinematics_plugin#39]
Before releasing (which I think this is absolutely ready for!) we should discuss about the prefix:

![grafik](https://user-images.githubusercontent.com/372442/77936200-dc0ff580-72b2-11ea-8849-9fc4e7d65c9b.png)

it kind of sticks out

**Comment by JeroenDM** [comment]
We could rewind history #1 :)
I don't have strong opinions on this, although I like short (but clear) names in general.

**Comment by simonschmeisser** [comment]
Haha, well, I don't care too much either so let's stick with the current one :)
