### ISSUE TITLE
What KinematicsBase function to use for returning all IK solutions?

### ISSUE THREAD

**Issue by JeroenDM** [JeroenDM/moveit_opw_kinematics_plugin#4]
I defined [this function](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/blob/325b509c080ddacbb2db64154ae30ce958ad7863/src/moveit_opw_kinematics_plugin.cpp#L39) to return all valid solutions calculated by opw_kinematics. This does not seem right. I could not find an example in the [universal robot kinematics plugin](https://github.com/ros-industrial/universal_robot/tree/kinetic-devel/ur_kinematics).

This is related to the fact that [descartes](https://github.com/ros-industrial-consortium/descartes) uses a custom MoveIt! wrapper to get all the soluitons, as discussed [here](https://github.com/ros-industrial-consortium/descartes/issues/215) and [here](https://answers.ros.org/question/285290/kdl-ik-fails-in-descartes/).

**Comment by JeroenDM** [comment]
Based on [this discussion](https://github.com/ros-planning/moveit_ikfast/pull/57) I think I did use the right function. Also, the obvious fact that it is [implemented that way](https://github.com/ros-planning/moveit/commit/33749ccfa531376042a9cc21b8f608c80ea674c3) in the ikfast plugin, which I somehow missed.

**Comment by simonschmeisser** [comment]
then let's reopen this?
