### ISSUE TITLE
Remove hard-coded 'prefix' in lookupParam(..) calls

### ISSUE THREAD

**Issue by gavanderhoorn** [JeroenDM/moveit_opw_kinematics_plugin#42]
Just remembered I removed it in 9135e4c76eeaf61a76328b34b7620d72df5969be and it seemed to work.

May be something to also include here.

**Comment by JeroenDM** [comment]
Mmm, I saw that commit and wondered what it was :) Thanks for the reminder. I'm not up to date on the problem I described there
>  // Using the full parameter name at the moment because the leading slash
>   // in front of robot_description_kinematics is missing
>   // in lookupParam function, but I'm not sure if this is a bug or I do not
>   // understand the interface.

but I'll just try to merge it see if tests fail or not.
