### ISSUE TITLE
Prune (old) branches?

### ISSUE THREAD

**Issue by gavanderhoorn** [JeroenDM/moveit_opw_kinematics_plugin#54]
There are quite a few branches in this repository and it's somewhat difficult to figure out what is still relevant.

@JeroenDM: would it make sense to prune some of the branches?

**Comment by JeroenDM** [comment]
Agreed. I already did it once, but there's been quite some activity this last month :)
I added it to my TODO list for the weekend.

Also, slightly of topic, but I'm in doubt whether to release from the devel branches to keep things simple, or create kinetic and melodic branches for the release.

**Comment by simonschmeisser** [comment]
keep it simple sounds good to me!

**Comment by JeroenDM** [comment]
I cleaned out all the merged branches. (That was scary! I hope I didn't miss any consequences that my come of this.)

Also, I changed the default branch to melodic-devel.

I'll keep it simple then regarding the release branches.

**Comment by JeroenDM** [comment]
Note, I also added protection to the two main branches, requiring at least 1 review and Travis passing before merging is allowed.

**Comment by gavanderhoorn** [comment]
> That was scary! I hope I didn't miss any consequences that my come of this.)

If those branches were used in old PRs, you would only have to revisit the PRs and click the "remove branch" button which shows up after you've merged the PR.

That way you can be certain you only remove branches which have actually been merged.

**Comment by JeroenDM** [comment]
Thanks for the tip!
