### ISSUE TITLE
Register repository 'doc job'

### ISSUE THREAD

**Issue by gavanderhoorn** [JeroenDM/moveit_opw_kinematics_plugin#65]
There doesn't appear to be a `doc` job registered for this package in `ros/rosdistro` ([kinetic](https://github.com/ros/rosdistro/blob/402c5b7bfdf1c6b639af03c130deec071375aa93/kinetic/distribution.yaml#L7690-L7700), [melodic](https://github.com/ros/rosdistro/blob/402c5b7bfdf1c6b639af03c130deec071375aa93/melodic/distribution.yaml#L5471-L5481)).

This is relatively trivial, but make the presence on the ROS wiki a bit nicer: [wiki/moveit_opw_kinematics_plugin](http://wiki.ros.org/moveit_opw_kinematics_plugin).

I can do it, but didn't want to do this without your approval @JeroenDM.

**Comment by JeroenDM** [comment]
:+1:

**Comment by JeroenDM** [comment]
It's unfortunate that the failing tests are so prominently featured on the doc page :)

**Comment by gavanderhoorn** [comment]
> It's unfortunate that the failing tests are so prominently featured on the doc page :)

Ha :)

I actually added that and it was done on purpose, so as to motivate developers to work on the quality of their packages.

Seems to be working :)

**Comment by gavanderhoorn** [comment]
https://github.com/ros/rosdistro/pull/25219
https://github.com/ros/rosdistro/pull/25220
