### ISSUE TITLE
moveit resources package is changing

### ISSUE THREAD

**Issue by JeroenDM** [JeroenDM/moveit_opw_kinematics_plugin#66]
Note to self:
https://github.com/ros-planning/moveit/pull/2199

**Comment by tylerjw** [comment]
As far as I can tell this is the reason this package doesn't build ( or run ) the tests when I do the pre-release melodic tests for moveit.  When I went and tried to do it manually (outside of the prerelease scripts I this output when trying to build the tests for this package):

```
WARNING: package "moveit_opw_kinematics_plugin" should not depend on metapackage "moveit_resources" but on its packages instead                                                                              
Abandoned <<< moveit_opw_kinematics_plugin                                   [ Depends on unknown jobs: moveit_resources ] 
```

**Comment by JeroenDM** [comment]
Thank you for the reminder! I completely forgot about it. I'll update the dependency.

As far as I remember the tests never ran because of the unreleased dependency #63.

**Comment by JeroenDM** [comment]
#71 

Links to use when I have the time
http://wiki.ros.org/bloom/Tutorials/PrereleaseTest
http://wiki.ros.org/bloom/Tutorials/ReleaseCatkinPackage
