### ISSUE TITLE
Fix CI or switch to Github actions

### ISSUE THREAD

**Issue by JeroenDM** [JeroenDM/moveit_opw_kinematics_plugin#72]
CI is not working properly, see #71.

Either make sure my account on the new `travis-ci.com` works or switch to Github actions.

**Comment by gavanderhoorn** [comment]
Travis has instituted limitations on use of their service(s) for OSS repositories (ie: a "new pricing structure").

Lots of repositories have already migrated to Github Actions.

I've recently done this for `ros-industrial/fanuc`, see ros-industrial/fanuc#300. It's still `industrial_ci` based, which supports GHA.

Alternatively, you could see whether [ros-tooling/action-ros-ci](https://github.com/ros-tooling/action-ros-ci) works for you.

And all of this until MS makes GHA also paid of course ;)
